export const emotionMap = {
  disappointment: "😞",
  sadness: "😢",
  annoyance: "😠",
  neutral: "😐",
  disapproval: "👎",
  realization: "💡",
  nervousness: "😰",
  approval: "👍",
  joy: "😄",
  anger: "😡",
  embarrassment: "😳",
  caring: "❤️",
  remorse: "😔",
  disgust: "🤢",
  grief: "💔",
  confusion: "😕",
  relief: "😌",
  desire: "😍",
  admiration: "😊",
  optimism: "😊",
  fear: "😨",
  love: "❤️",
  excitement: "😃",
  curiosity: "🤔",
  amusement: "😆",
  surprise: "😲",
  gratitude: "🙏",
  pride: "🏆",
};
