export const testData = [
  { sentence: "Capitalism is absolutely sickening", emoji: "🤢" },
  {
    sentence: "I can't stand the injustice in this world anymore",
    emoji: "😡",
  },
  { sentence: "This smell makes me want to vomit", emoji: "🤢" },
  { sentence: "The thought of failing terrifies me", emoji: "😨" },
  { sentence: "I'm thrilled to see you!", emoji: "😄" },
  { sentence: "The news of her passing broke my heart", emoji: "😢" },
  { sentence: "The magician's trick left me in awe", emoji: "😲" },
  { sentence: "The corruption in politics is nauseating", emoji: "🤢" },
  { sentence: "The sight of blood always makes me queasy", emoji: "🤢" },
  {
    sentence: "I'm infuriated by their blatant disregard for the truth",
    emoji: "😡",
  },
  { sentence: "Just thinking about spiders gives me the creeps", emoji: "😨" },
  { sentence: "I'm overjoyed to finally meet you!", emoji: "😄" },
  { sentence: "His betrayal left me feeling utterly devastated", emoji: "😢" },
  { sentence: "The unexpected plot twist left me speechless", emoji: "😲" },
  { sentence: "The stench from the garbage is revolting", emoji: "🤢" },
  { sentence: "I'm seething with anger at their dishonesty", emoji: "😡" },
  { sentence: "The looming threat of failure is paralyzing", emoji: "😨" },
  { sentence: "This news fills me with immense happiness", emoji: "😄" },
  { sentence: "Her resignation letter brought tears to my eyes", emoji: "😢" },
  { sentence: "The unexpected surprise left me wide-eyed", emoji: "😲" },
  { sentence: "The hypocrisy of their actions makes me sick", emoji: "🤢" },
  { sentence: "The decaying food emits a foul odor", emoji: "🤢" },
  { sentence: "I'm boiling with rage over their incompetence", emoji: "😡" },
  {
    sentence: "The eerie silence of the forest sends shivers down my spine",
    emoji: "😨",
  },
  { sentence: "I'm elated to hear about your success!", emoji: "😄" },
  { sentence: "The tragic news left me in tears", emoji: "😢" },
  { sentence: "The unexpected announcement left me wide-mouthed", emoji: "😲" },
  { sentence: "The vile actions of the perpetrator disgust me", emoji: "🤢" },
  { sentence: "The sight of maggots makes me nauseous", emoji: "🤢" },
  { sentence: "I'm fuming with anger over their betrayal", emoji: "😡" },
  { sentence: "The looming thunderstorm fills me with dread", emoji: "😨" },
  { sentence: "I'm beaming with joy at your accomplishment!", emoji: "😄" },
  { sentence: "The heartbreaking loss brought tears to my eyes", emoji: "😢" },
  { sentence: "The unexpected revelation left me in shock", emoji: "😲" },
  { sentence: "The putrid smell of rotten eggs is sickening", emoji: "🤢" },
  { sentence: "Their lies make my skin crawl", emoji: "😡" },
  {
    sentence:
      "The chilling atmosphere of the abandoned house fills me with fear",
    emoji: "😨",
  },
  { sentence: "I'm ecstatic about your engagement!", emoji: "😄" },
  { sentence: "The tragic news left me in despair", emoji: "😢" },
  { sentence: "The unexpected turn of events left me speechless", emoji: "😲" },
  {
    sentence: "The revolting behavior of the bullies makes me sick",
    emoji: "🤢",
  },
  {
    sentence: "The foul odor emanating from the sewer is nauseating",
    emoji: "🤢",
  },
  { sentence: "I'm enraged by their deceitful actions", emoji: "😡" },
  {
    sentence: "The eerie silence of the graveyard sends chills down my spine",
    emoji: "😨",
  },
  { sentence: "I'm over the moon about your promotion!", emoji: "😄" },
  {
    sentence: "The heart-wrenching news brought tears to my eyes",
    emoji: "😢",
  },
  {
    sentence: "The unexpected twist in the plot left me wide-eyed",
    emoji: "😲",
  },
  {
    sentence: "The nauseating smell of spoiled milk makes me gag",
    emoji: "🤢",
  },
  { sentence: "I'm seething with fury at their incompetence", emoji: "😡" },
  {
    sentence: "The bone-chilling howl of the wind fills me with fear",
    emoji: "😨",
  },
  { sentence: "I'm thrilled to finally see you again!", emoji: "😄" },
  { sentence: "The tragic news left me heartbroken", emoji: "😢" },
  { sentence: "The unexpected outcome left me in disbelief", emoji: "😲" },
];
